iris数据集练习
1.加载数据的方式分为两种，一种是load，一种是fetch
load是从本地加载，fetch是从网络上下载
2.练习train_test_split

In [2]:
#
from sklearn.datasets import load_iris #
from sklearn.model_selection import train_test_split #

In [12]:
#鸢尾花数据集，查看特征，目标，样本量

li = load_iris()

print("获取Iris特征值")
print(type(li)) #<class 'sklearn.utils._bunch.Bunch'>
print('-' * 50)
print(type(li.data))# li的data都是ndarry
print('-' * 50)
print(li.data[0:3])# 前三个样本特征值
print('-' * 50)
print(li.data.shape) # 150个样本，4个特征,一般看shape
print("目标值")
print(li.target) # 目标值
print('-' * 50)
print(" feature_names")
print(li.feature_names)  # 重点,特征名字
print('-' * 50)
print(" target_names")
print(li.target_names) # 目标名字
print('-' * 50)
print(" DESCR")
print(li.DESCR) # 数据集描述
print('-' * 50)

获取Iris特征值
<class 'sklearn.utils._bunch.Bunch'>
--------------------------------------------------
<class 'numpy.ndarray'>
--------------------------------------------------
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
--------------------------------------------------
(150, 4)
目标值
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
--------------------------------------------------
 feature_names
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
--------------------------------------------------
 target_names
['setosa' 'versicolor' 'virginica']
--------------------------------------------------
 DESCR
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**


In [16]:
#x 是特征值
#y 是标签值，也是目标名，比如说分类问题，已知最终的类别有哪些，那些类就是他们的标签名
# 注意返回值, 训练集 train  x_train, y_train        测试集  test   x_test, y_test，顺序千万别搞错了
# 默认是乱序的,random_state为了确保两次的随机策略一致，就会得到相同的随机数据，往往会带上

x_train, x_test, y_train, y_test = train_test_split(li.data, li.target, test_size=0.25, random_state=1)

print("训练集特征值shape", x_train.shape)#150/4*3=112
print('-'*50)
print("测试集特征值shape", x_test.shape)#150/4
print('-'*50)

print("训练集特征值和目标值：", x_train, y_train)#目标值就三种，所以012
print('-'*50)
print("测试集特征值和目标值：", x_test, y_test)
print('-'*50)

训练集特征值shape (112, 4)
--------------------------------------------------
测试集特征值shape (38, 4)
--------------------------------------------------
训练集特征值和目标值： [[6.5 2.8 4.6 1.5]
 [6.7 2.5 5.8 1.8]
 [6.8 3.  5.5 2.1]
 [5.1 3.5 1.4 0.3]
 [6.  2.2 5.  1.5]
 [6.3 2.9 5.6 1.8]
 [6.6 2.9 4.6 1.3]
 [7.7 2.6 6.9 2.3]
 [5.7 3.8 1.7 0.3]
 [5.  3.6 1.4 0.2]
 [4.8 3.  1.4 0.3]
 [5.2 2.7 3.9 1.4]
 [5.1 3.4 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [7.7 3.8 6.7 2.2]
 [6.9 3.1 5.4 2.1]
 [7.3 2.9 6.3 1.8]
 [6.4 2.8 5.6 2.2]
 [6.2 2.8 4.8 1.8]
 [6.  3.4 4.5 1.6]
 [7.7 2.8 6.7 2. ]
 [5.7 3.  4.2 1.2]
 [4.8 3.4 1.6 0.2]
 [5.7 2.5 5.  2. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.  1.4 0.1]
 [4.7 3.2 1.3 0.2]
 [6.5 3.  5.8 2.2]
 [4.6 3.4 1.4 0.3]
 [6.1 3.  4.9 1.8]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.4 1.4]
 [5.7 2.8 4.5 1.3]
 [6.7 3.3 5.7 2.5]
 [6.  3.  4.8 1.8]
 [5.1 3.8 1.6 0.2]
 [6.  2.2 4.  1. ]
 [6.4 2.9 4.3 1.3]
 [6.5 3.  5.5 1.8]
 [5.  2.3 3.3 1. ]
 [6.3 3.3 6.  2.5]
 [5.5 2.5 4.  1.3]
 [5.4 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.2]
 [5.2 4.1

In [1]:
from sklearn.datasets import fetch_20newsgroups

In [8]:
# 下面是比较大的数据，需要下载一会，20类新闻
#subset代表下载的数据集类型，默认是train，只有训练集
news = fetch_20newsgroups(subset='all', data_home='../machine_learn/data')
# print(news.feature_names)  #这个数据集是没有的
# print(news.DESCR)
print('第一个样本')
print(news.data[0])
print('特征类型')
print(type(news.data))#list
print('-' * 50)
print(len(news.data))#有18846个样本
print('-' * 50)
print(news.target[0:3]) #前三个样本的标签分别是10，3，17
print('-' * 50)
# print(news.data.shape)
print('-' * 50)
print('新闻所有的标签')
print(news.target)
print('-' * 50)
print(min(news.target), max(news.target))
print('-' * 50)
print(news.DESCR)

第一个样本
From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>
Subject: Pens fans reactions
Organization: Post Office, Carnegie Mellon, Pittsburgh, PA
Lines: 12
NNTP-Posting-Host: po4.andrew.cmu.edu



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!


特征类型
<class 'list'>
--------------------------------------------------
18846
--------------

In [10]:
from sklearn.datasets import load_boston#被remove了

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [11]:
from sklearn.datasets import fetch_california_housing

In [13]:
house=fetch_california_housing(data_home='../machine_learn/data')
print("获取特征值")
print(house.data[0])  #第一个样本特征值
print('样本的形状')
print(house.data.shape)# (20640, 8)
print('-' * 50)
print("目标值的名字")
print(house.target_names) #['MedHouseVal']
print('-' * 50)
print("目标值")
print(house.target)
print('-' * 50)
print("特征值的名字")
print(house.feature_names)
print('-' * 50)
print(house.DESCR)


获取特征值
[   8.3252       41.            6.98412698    1.02380952  322.
    2.55555556   37.88       -122.23      ]
样本的形状
(20640, 8)
--------------------------------------------------
目标值的名字
['MedHouseVal']
--------------------------------------------------
目标值
[4.526 3.585 3.521 ... 0.923 0.847 0.894]
--------------------------------------------------
特征值的名字
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
--------------------------------------------------
.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household